/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/B.gltf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/B.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.AB_text_0.geometry} material={materials['text.003']} scale={0.01} />
    </group>
  )
}

useGLTF.preload('/B.gltf')
