/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/ufo.gltf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/ufo.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI, 0, -Math.PI]} scale={[-2, -0.48, -2]}>
        <mesh geometry={nodes.Object_4.geometry} material={materials.Body} />
        <mesh geometry={nodes.Object_5.geometry} material={materials['Glass.001']} />
        <mesh geometry={nodes.Object_6.geometry} material={materials['Dome.belt']} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.Bottom} />
        <mesh geometry={nodes.Object_8.geometry} material={materials['Glass.mini']} />
        <mesh geometry={nodes.Object_9.geometry} material={materials['Bottom.001']} />
      </group>
    </group>
  )
}

useGLTF.preload('/ufo.gltf')
