/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/burger.gltf
*/

// burger props
// <Burger tomato={false} lettuce={false} cheese={true} patty={false} topBun={false} bottomBun={true}/>

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Burger(props) {
  const { nodes, materials } = useGLTF('/burger.gltf')
  
  return (
    <group {...props} dispose={null} rotation={[Math.PI, 0, Math.PI]}>
      <group position={[0, 0.83, 0]} rotation={[-1.74, 0.12, -0.03]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          { props.topBun &&
          <group position={[-0.12, 0.57, 0.13]} rotation={[0.18, 0.02, 0.12]} scale={[1.54, 0.48, 1.54]}>
            <mesh geometry={nodes.Object_4.geometry} material={materials['Material.004']} position={[0, 0.26, 0]} />
          </group>
          }
          {/* lettuce */}
          { props.lettuce &&
          <group position={[-0.06, 0.1, 0.05]} rotation={[0.18, 0.02, 0.12]} scale={[1.61, 0.05, 1.61]}>
            <mesh geometry={nodes.Object_6.geometry} material={materials['Material.003']} position={[0, 2.34, 0]} scale={1.03} />
          </group>
          }
          { props.patty &&
          <mesh geometry={nodes.Object_8.geometry} material={materials['Material.002']} position={[-0.04, -0.07, 0.02]} rotation={[0.18, 0.02, 0.12]} scale={[1.52, 0.21, 1.52]} />
          }
          { props.bottomBun &&
          <mesh geometry={nodes.Object_12.geometry} material={materials['Material.004']} position={[0.03, -0.64, -0.09]} rotation={[0.18, 0.02, -3.02]} scale={[1.5, 0.36, 1.5]} />
          }
          { props.cheese && 
          <mesh geometry={nodes.Object_10.geometry} material={materials['Material.001']} position={[-0.02, -0.23, -0.01]} rotation={[0.24, -0.41, 0.14]} scale={1.45} />
          }
        </group>
      </group>
      {/* tomato */}
      {props.tomato &&
      <group position={[0, 2.19, 0]} rotation={[-1.74, 0.12, -0.03]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[-0.04, -0.07, 0.02]} rotation={[0.18, 0.02, 0.12]} scale={[1.52, 0.21, 1.52]}>
            <mesh geometry={nodes.Object_8001.geometry} material={materials['Material.005']} position={[-0.01, -5.43, 0]} scale={[1.12, 0.38, 1.12]} />
          </group>
        </group>
      </group>
}
    </group>
  )
}

useGLTF.preload('/burger.gltf')
