/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/characters.gltf
*/
import * as THREE from 'three'
import React, { useRef, useState } from 'react'
import { Float, useGLTF, useScroll } from '@react-three/drei'
import { useFrame, useThree } from '@react-three/fiber'
import { Physics, usePlane, useBox } from '@react-three/cannon'
import { BurgerUnfixed } from './BurgerUnfixed'

function Patty(props) {  
  const [ref] = useBox(() => ({ mass: 0.25, position: [0, 0, 0], args: [1, 0.3, 1] ,...props }))
  return (
    <mesh ref={ref}>
      <BurgerUnfixed patty={true}/>
      </mesh>
  )
}

function TopBun(props) {  
  const [ref] = useBox(() => ({ mass: 0.25, position: [0, 0, 0], args: [10, 0.65, 10] ,...props }))
  return (
    <mesh ref={ref}>
      <BurgerUnfixed topBun={true}/>
      </mesh>
  )
}

function BottomBun(props) {  
  const [ref] = useBox(() => ({ mass: 0.25, position: [0, 0, 0], args: [10, 0.65, 10] ,...props }))
  return (
    <mesh ref={ref}>
      <BurgerUnfixed bottomBun={true}/>
      </mesh>
  )
}

function Tomato(props) {  
  const [ref] = useBox(() => ({ mass: 0.25, position: [0, 0, 0], args: [10, 0.13, 10] ,...props }))
  return (
    <mesh ref={ref}>
      <BurgerUnfixed tomato={true}/>
      </mesh>
  )
}

function Lettuce(props) {  
  const [ref] = useBox(() => ({ mass: 0.25, position: [0, 0, 0], args: [10, 0.107, 10] ,...props }))
  return (
    <mesh ref={ref}>
      <BurgerUnfixed lettuce={true}/>
      </mesh>
  )
}

function Cheese(props) {  
  const [ref] = useBox(() => ({ mass: 0.25, position: [0, 0, 0], args: [10, 0.11, 10] ,...props }))
  return (
    <mesh ref={ref}>
      <BurgerUnfixed cheese={true}/>
      </mesh>
  )
}

function Plane(props) {
  const [ref] = usePlane(() => ({ rotation: [-Math.PI / 2, 0, 0], ...props }))
  return (
    <mesh ref={ref} receiveShadow >
      <planeGeometry args={[1000, 1000]} />
      <shadowMaterial color="#171717" transparent opacity={0.4} />
    </mesh>
  )
}

export function BurgerMake(props) {

    // CALCULATING WIDTH AND HEIGHT OF THE SCREEN
    const { width, height } = useThree((state) => state.viewport)
    const scroll = useScroll( )
    const [burgerY, setBurgerY] = useState(0)
    const mesh = useRef()
    const { viewport } = useThree()
    const [characterScale, setCharacterScale] = useState(0)

    // ROTATION
    useFrame((state, delta) => {
      const r1 = scroll.range(0, 1 / 4)
      const r2 = scroll.range(1 / 4, 1 / 4)
      const r3 = scroll.visible(4 / 5, 1 / 5)
  //    mesh.current.rotation.y += r1/10
      setCharacterScale(scroll.range(0, 1 / 2) * 10 + 1)
    })

  useFrame((state, delta) => {
    setBurgerY(scroll.range(0.8, 2 / 9) * 10 - 9)
    mesh.current.rotation.y += delta
  })
    return (
    <>  
        <Physics>
        <group ref={mesh} position={[-0.05, burgerY, 0.07]}>
        <Plane position={[0,-2,0]}/>
        { 
            props.pattyShow[0] && <Patty position={[0,5,0]}/>
        }
        { 
            props.pattyShow[1] && <Patty position={[0,5,0]}/>
        }
        { 
            props.cheeseShow[0] && <Cheese position={[0,5,0]}/>
        }
        { 
            props.cheeseShow[1] && <Cheese position={[0,5,0]}/>
        }
        { 
            props.topBunShow[0] && <TopBun position={[0,5,0]}/>
        }
        { 
            props.topBunShow[1] && <TopBun position={[0,5,0]}/>
        }
        { 
            props.bottomBunShow[0] && <BottomBun position={[0,5,0]}/>
        }
        { 
            props.bottomBunShow[1] && <BottomBun position={[0,5,0]}/>
        }
        { 
            props.lettuceShow[0] && <Lettuce position={[0,5,0]}/>
        }
        { 
            props.lettuceShow[1] && <Lettuce position={[0,5,0]}/>
        }
        { 
            props.tomatoShow[0] && <Tomato position={[0,5,0]}/>
        }
        { 
            props.tomatoShow[1] && <Tomato position={[0,5,0]}/>
        }
        </group>
        </Physics>
    </>
  )
}

useGLTF.preload('/characters.gltf')
