/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/scene.gltf
Author: naira001 (https://sketchfab.com/naira001)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/simple-alphabet-86bc96d947054d9398402069c02f96fc
Title: Simple alphabet
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default  function Model(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh geometry={nodes.AMesh_numbers_0.geometry} material={materials.numbers} />
        <mesh geometry={nodes.AA_text_0.geometry} material={materials.text} />
        <mesh geometry={nodes.AB_text_0.geometry} material={materials.text} />
        <mesh geometry={nodes.AC_text_0.geometry} material={materials.text} />
        <mesh geometry={nodes.AD_text_0.geometry} material={materials.text} />
        <mesh geometry={nodes.AE_text_0.geometry} material={materials.text} />
        <mesh geometry={nodes.AF_text_0.geometry} material={materials.text} />
        <mesh geometry={nodes.AG_text_0.geometry} material={materials.text} />
        <mesh geometry={nodes.AH_text_0.geometry} material={materials.text} />
        <mesh geometry={nodes.AO_text_0.geometry} material={materials.text} />
        <mesh geometry={nodes.AI_text_0.geometry} material={materials.text} />
        <mesh geometry={nodes.AJ_text_0.geometry} material={materials.text} />
        <mesh geometry={nodes.AQ_text_0.geometry} material={materials.text} />
        <mesh geometry={nodes.AL_text_0.geometry} material={materials.text} />
        <mesh geometry={nodes.AK_text_0.geometry} material={materials.text} />
        <mesh geometry={nodes.AM_text_0.geometry} material={materials.text} />
        <mesh geometry={nodes.AN_text_0.geometry} material={materials.text} />
        <mesh geometry={nodes.AP_text_0.geometry} material={materials.text} />
        <mesh geometry={nodes.AR_text_0.geometry} material={materials.text} />
        <mesh geometry={nodes.AS_text_0.geometry} material={materials.text} />
        <mesh geometry={nodes.AV_text_0.geometry} material={materials.text} />
        <mesh geometry={nodes.AX_text_0.geometry} material={materials.text} />
        <mesh geometry={nodes.AY_text_0.geometry} material={materials.text} />
        <mesh geometry={nodes.AT_text_0.geometry} material={materials.text} />
        <mesh geometry={nodes.AU_text_0.geometry} material={materials.text} />
        <mesh geometry={nodes.AW_text_0.geometry} material={materials.text} />
        <mesh geometry={nodes.AZ_text_0.geometry} material={materials.text} />
        <mesh geometry={nodes.AMesh1_numbers_0.geometry} material={materials.numbers} />
        <mesh geometry={nodes.AMesh2_numbers_0.geometry} material={materials.numbers} />
        <mesh geometry={nodes.AMesh3_numbers_0.geometry} material={materials.numbers} />
        <mesh geometry={nodes.AMesh4_numbers_0.geometry} material={materials.numbers} />
        <mesh geometry={nodes.AMesh5_numbers_0.geometry} material={materials.numbers} />
        <mesh geometry={nodes.AMesh6_numbers_0.geometry} material={materials.numbers} />
        <mesh geometry={nodes.AMesh7_numbers_0.geometry} material={materials.numbers} />
        <mesh geometry={nodes.AMesh8_numbers_0.geometry} material={materials.numbers} />
        <mesh geometry={nodes.AMesh9_numbers_0.geometry} material={materials.numbers} />
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
